development:
  host: localhost
  adapter: postgresql
  database: xena
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  host: localhost
  adapter: postgresql
  database: xena_TEST
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
