class Api::V1::StampSerializer < ActiveModel::Serializer

  attributes :id,
             :country_name,
             :sub_country_name,
             :set_description,
             :set_text,
             :set_designer,
             :set_start_year,
             :set_start_month,
             :set_start_day,
             :set_end_year,
             :set_end_month,
             :set_end_day,
             :set_perf_info,
             :set_type_number,
             :set_watermark_number,
             :sg_number,
             :stamp_prefix,
             :stamp_sg_number,
             :stamp_pre_suffix,
             :stamp_suffix,
             :stamp_description,
             :variety_description,
             :stamp_issue_price,
             :stamp_type_number,
             :stamp_unused,
             :stamp_used,
             :variety_flag,
             :image_url,
             :computed_description,
             :local_image_url

end
